//! Matching engine for the order book.

use std::collections::VecDeque;
use serde::{Serialize, Deserialize};
use crate::order_book::{
    OrderBook, Order, OrderId, Price, Quantity, Timestamp, ClientId, 
    OrderSide, OrderType, TimeInForce
};

/// Matching engine configuration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MatchingEngineConfig {
    /// Maximum number of orders to match in a single pass
    pub max_match_orders: usize,
    /// Maximum number of trades to generate in a single pass
    pub max_trades: usize,
    /// Enable self-matching (matching orders from the same client)
    pub enable_self_matching: bool,
}

impl Default for MatchingEngineConfig {
    fn default() -> Self {
        Self {
            max_match_orders: 1000,
            max_trades: 10000,
            enable_self_matching: false,
        }
    }
}

/// Result of matching an order
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MatchResult {
    /// List of trades generated
    pub trades: Vec<Trade>,
    /// Remaining order (if any)
    pub remaining_order: Option<Order>,
}

/// Trade generated by matching engine
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Trade {
    /// Trade ID
    pub id: uuid::Uuid,
    /// Buy order ID
    pub buy_order_id: OrderId,
    /// Sell order ID
    pub sell_order_id: OrderId,
    /// Price of the trade
    pub price: Price,
    /// Quantity of the trade
    pub quantity: Quantity,
    /// Timestamp of the trade
    pub timestamp: Timestamp,
    /// Aggressor side (which side initiated the trade)
    pub aggressor_side: OrderSide,
}

/// Matching engine for the order book
#[derive(Debug)]
pub struct MatchingEngine {
    /// Order book
    order_book: OrderBook,
    /// Configuration
    config: MatchingEngineConfig,
    /// Queue of orders to process
    order_queue: VecDeque<Order>,
    /// List of trades generated
    trades: Vec<Trade>,
}

impl MatchingEngine {
    /// Create a new matching engine
    pub fn new(order_book: OrderBook, config: MatchingEngineConfig) -> Self {
        Self {
            order_book,
            config,
            order_queue: VecDeque::new(),
            trades: Vec::new(),
        }
    }
    
    /// Add a limit order to the book
    pub fn add_limit_order(
        &mut self,
        side: OrderSide,
        price: Price,
        quantity: Quantity,
        client_id: ClientId,
        time_in_force: TimeInForce,
    ) -> anyhow::Result<MatchResult> {
        // Create order
        let order = Order::new_limit(side, price, quantity, client_id, time_in_force);
        
        // Match order
        self.match_order(order)
    }
    
    /// Add a market order to the book
    pub fn add_market_order(
        &mut self,
        side: OrderSide,
        quantity: Quantity,
        client_id: ClientId,
    ) -> anyhow::Result<MatchResult> {
        // Create order
        let order = Order::new_market(side, quantity, client_id);
        
        // Match order
        self.match_order(order)
    }
    
    /// Cancel an order
    pub fn cancel_order(&mut self, order_id: &OrderId) -> anyhow::Result<Order> {
        self.order_book.cancel_order(order_id).map_err(|e| anyhow::anyhow!(e.to_string()))
    }
    
    /// Match an order
    fn match_order(&mut self, order: Order) -> anyhow::Result<MatchResult> {
        let mut trades = Vec::new();
        let mut remaining_order = Some(order.clone());
        
        // Check if the order can be matched
        match order.side {
            OrderSide::Buy => {
                // Match against the ask side
                if let Some(best_ask) = self.order_book.best_ask() {
                    if order.order_type == OrderType::Market || order.price >= best_ask {
                        // Order can be matched
                        let result = self.match_against_asks(order.clone())?;
                        trades = result.trades;
                        remaining_order = result.remaining_order;
                    }
                }
            }
            OrderSide::Sell => {
                // Match against the bid side
                if let Some(best_bid) = self.order_book.best_bid() {
                    if order.order_type == OrderType::Market || order.price <= best_bid {
                        // Order can be matched
                        let result = self.match_against_bids(order.clone())?;
                        trades = result.trades;
                        remaining_order = result.remaining_order;
                    }
                }
            }
        }
        
        // Add the remaining order to the book if it's a limit order
        let final_remaining_order = if let Some(remaining) = remaining_order {
            if remaining.remaining_quantity > 0.0 && remaining.order_type == OrderType::Limit {
                match remaining.time_in_force {
                    TimeInForce::IOC => None, // IOC orders are canceled if not filled immediately
                    TimeInForce::FOK => {
                        if trades.is_empty() {
                            None // FOK orders are canceled if not filled completely
                        } else {
                            Some(remaining)
                        }
                    }
                    _ => {
                        // Add to the book
                        self.order_book.add_limit_order(
                            remaining.side,
                            remaining.price,
                            remaining.remaining_quantity,
                            remaining.client_id.clone(),
                            remaining.time_in_force,
                        )?;
                        Some(remaining)
                    }
                }
            } else {
                None
            }
        } else {
            None
        };
        
        Ok(MatchResult {
            trades,
            remaining_order: final_remaining_order,
        })
    }
    
    /// Match an order against the ask side
    fn match_against_asks(&mut self, mut order: Order) -> anyhow::Result<MatchResult> {
        let mut trades = Vec::new();
        
        // Match until the order is filled or there are no more asks
        while order.remaining_quantity > 0.0 {
            if let Some(best_ask) = self.order_book.best_ask() {
                if order.order_type == OrderType::Limit && order.price < best_ask {
                    // No more matching possible
                    break;
                }
                
                // Get the top ask orders
                let top_asks = self.order_book.top_asks(1);
                
                if top_asks.is_empty() {
                    // No more asks
                    break;
                }
                
                let (ask_price, _ask_quantity) = top_asks[0];
                
                // Get the ask order
                let ask_order = self.order_book.get_order(&OrderId(uuid::Uuid::nil()));
                
                if ask_order.is_none() {
                    // No more asks
                    break;
                }
                
                let mut ask_order = ask_order.unwrap();
                
                // Check if self-matching is allowed
                if !self.config.enable_self_matching && order.client_id == ask_order.client_id {
                    // Skip this order
                    continue;
                }
                
                // Calculate the match quantity
                let match_quantity = order.remaining_quantity.min(ask_order.remaining_quantity);
                
                // Create a trade
                let trade = Trade {
                    id: uuid::Uuid::new_v4(),
                    buy_order_id: order.id,
                    sell_order_id: ask_order.id,
                    price: ask_price,
                    quantity: match_quantity,
                    timestamp: chrono::Utc::now().timestamp_nanos_opt().unwrap_or(0) as u64,
                    aggressor_side: order.side,
                };
                
                // Update the orders
                order.remaining_quantity -= match_quantity;
                ask_order.remaining_quantity -= match_quantity;
                
                // Add the trade
                trades.push(trade);
                
                // Update the ask order in the book
                if ask_order.remaining_quantity <= 0.0 {
                    // Remove the ask order from the book
                    self.order_book.cancel_order(&ask_order.id)?;
                }
                
                // Check if we've reached the maximum number of trades
                if trades.len() >= self.config.max_trades {
                    break;
                }
            } else {
                // No more asks
                break;
            }
        }
        
        Ok(MatchResult {
            trades,
            remaining_order: Some(order),
        })
    }
    
    /// Match an order against the bid side
    fn match_against_bids(&mut self, mut order: Order) -> anyhow::Result<MatchResult> {
        let mut trades = Vec::new();
        
        // Match until the order is filled or there are no more bids
        while order.remaining_quantity > 0.0 {
            if let Some(best_bid) = self.order_book.best_bid() {
                if order.order_type == OrderType::Limit && order.price > best_bid {
                    // No more matching possible
                    break;
                }
                
                // Get the top bid orders
                let top_bids = self.order_book.top_bids(1);
                
                if top_bids.is_empty() {
                    // No more bids
                    break;
                }
                
                let (bid_price, _bid_quantity) = top_bids[0];
                
                // Get the bid order
                let bid_order = self.order_book.get_order(&OrderId(uuid::Uuid::nil()));
                
                if bid_order.is_none() {
                    // No more bids
                    break;
                }
                
                let mut bid_order = bid_order.unwrap();
                
                // Check if self-matching is allowed
                if !self.config.enable_self_matching && order.client_id == bid_order.client_id {
                    // Skip this order
                    continue;
                }
                
                // Calculate the match quantity
                let match_quantity = order.remaining_quantity.min(bid_order.remaining_quantity);
                
                // Create a trade
                let trade = Trade {
                    id: uuid::Uuid::new_v4(),
                    buy_order_id: bid_order.id,
                    sell_order_id: order.id,
                    price: bid_price,
                    quantity: match_quantity,
                    timestamp: chrono::Utc::now().timestamp_nanos_opt().unwrap_or(0) as u64,
                    aggressor_side: order.side,
                };
                
                // Update the orders
                order.remaining_quantity -= match_quantity;
                bid_order.remaining_quantity -= match_quantity;
                
                // Add the trade
                trades.push(trade);
                
                // Update the bid order in the book
                if bid_order.remaining_quantity <= 0.0 {
                    // Remove the bid order from the book
                    self.order_book.cancel_order(&bid_order.id)?;
                }
                
                // Check if we've reached the maximum number of trades
                if trades.len() >= self.config.max_trades {
                    break;
                }
            } else {
                // No more bids
                break;
            }
        }
        
        Ok(MatchResult {
            trades,
            remaining_order: Some(order),
        })
    }
}
